# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_letter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='letter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
