# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_letter', '0004_auto_20180203_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
